config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  root 'subgenres#index'
  resources :subgenres do
    resources :songs do


      member do
        post :upvote
        post :downvote
      end

    

   end

  end
end

app/models/song.rb
class Song < ActiveRecord::Base
  validates :title, :presence => true
  validates :artist, :presence => true
  validates :summary, :presence => true
  validates :comments, :presence => true
  belongs_to :subgenre
end

app/models/subgenre.rb
class Subgenre < ActiveRecord::Base
  validates :name, :presence => true
  has_many :songs, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def new
    @subgenres = Subgenre.find(params[:subgenre_id])
    @songs = @subgenres.songs.new
  end

  def create
    @subgenres = Subgenre.find(params[:subgenre_id])
    @songs = @subgenres.songs.new(song_params)
    if @songs.save
      redirect_to subgenre_path(@subgenres)
    else
      render 'new'
    end
  end

  def edit
    @subgenres = Subgenre.find(params[:subgenre_id])
    @songs = @subgenres.songs.find(params[:id])
  end

  def update
    @subgenres = Subgenre.find(params[:subgenre_id])
    @songs = @subgenres.songs.find(params[:id])
    if params[:vote] == "up"
      @songs.upvote += 1;
      @songs.save;
      redirect_to subgenre_path(@subgenres)
    elsif params[:vote] == "down"
      @songs = @subgenres.songs.find(params[:id])
      @songs.downvote += 1;
      @songs.save;
      redirect_to subgenre_path(@subgenres)
    else
      if @songs.update(song_params)
        redirect_to subgenre_path(@subgenres)
      else
        render :edit
      end
    end
  end

  def destroy
    @subgenres = Subgenre.find(params[:subgenre_id])
    @songs = @subgenres.songs.find(params[:id])
    @songs.destroy
    redirect_to subgenre_path(@subgenres)
  end

  def show
    @subgenres = Subgenre.find(params[:subgenre_id])
    @songs = @subgenres.songs.find(params[:id])
  end

<


  private
  def song_params
    params.require(:song).permit(:title, :artist, :summary, :comments, :subgenre_id)
  end
end

app/controllers/subgenres_controller.rb
class SubgenresController < ApplicationController
  def index
    @subgenres = Subgenre.all
    if Song.any?
      @random_song = Song.all.sample
    end
    @songs = Song.all
    render :index
  end

  def show
    @subgenres = Subgenre.find(params[:id])
    @songs = @subgenres.songs
    render :show
  end

  def new
    @subgenres = Subgenre.new
    render :new
  end

  def create
    @subgenres = Subgenre.new(subgenre_params)
    if @subgenres.save
      redirect_to  subgenres_path
    else
      render :new
    end
  end

  def edit
    @subgenres = Subgenre.find(params[:id])
    render :edit
  end

  def update
    @subgenres= Subgenre.find(params[:id])
    if @subgenres.update(subgenre_params)
      redirect_to subgenres_path
    else
      render :edit
    end
  end

  def destroy
    @subgenres = Subgenre.find(params[:id])
    @subgenres.destroy
    @subgenres.songs.destroy
    redirect_to subgenres_path

  end


  private
  def subgenre_params
    params.require(:subgenre).permit(:name)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<h3>Please fix these errors:</h3>
<ul>
  <% object.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HipHopHurray</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://bootswatch.com/darkly/bootstrap.min.css" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
  <div class="container">
    <div class="jumbotron">
      <h1>HipHopHurray</h1>
      <h4>We do it for tha streetz</h4>
    </div>
    <%= yield %>

    <hr>
    <center><%= link_to subgenres_path, class: "btn btn-success" do %>
      <i class="glyphicon glyphicon-home"> Home</i>
      <% end %></center>
  </div>
</body>
</html>

app/views/songs/_form.html.erb
<%= render "layouts/errors", :object => @songs %>

<h2>Add a new song to <%= @subgenres.name %></h2>

<%= form_for [@subgenres, @songs] do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :artist %>
<%= f.text_field :artist %>
<%= f.label :summary %>
<%= f.text_field :summary %>
<%= f.label :comments %>
<%= f.text_field :comments %>
<%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1>Edit Song</h1>

<%= render 'form' %>

app/views/songs/new.html.erb
<%= render 'form' %>

app/views/songs/show.html.erb
<h2> Song Title: "<%= @songs.title %>" </h2>

<br>
  <div id="back-button">
    <%= link_to subgenre_path(@subgenres), class: "btn btn-xs btn-success" do %>
    <i class="glyphicon glyphicon-chevron-left"> Back</i>
    <% end %>
  </div>
<br>

<h3> Artist: <%= @songs.artist %> </h3>

<br>

<h4> Artist Summary: </h4><p><%= @songs.summary %></p>

<br>

<h4> Poster's Comments: </h4> <p><%= @songs.comments %></p>

app/views/subgenres/_form.html.erb
<%= render "layouts/errors", :object => @subgenres %>

<%= form_for @subgenres do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit %>
<% end %>

app/views/subgenres/edit.html.erb
<h1>Edit Subgenre</h1>




<%= render "form" %>

app/views/subgenres/index.html.erb
<h3>Pick from different stylez || <small><%= link_to "Add new stylez", new_subgenre_path %></small></h3>

<ul>
  <% @subgenres.each do |subgenre| %>
    <h4><big><li><%= link_to subgenre.name, subgenre_path(subgenre)  %></li></big></h4>
      <h5>Top 3 Songs: </h5>
        <% subgenre.songs.order(upvote: :desc).first(3).each do |song| %>
        <li> <big><%= link_to song.title, subgenre_song_path(subgenre, song)  %></big>
          - by <em><%= song.artist %></em>
          - posted <%= time_ago_in_words(song.created_at)  %> ago
          - <%= song.upvote %> upvotes</li>
        <% end %>
    <% end %>
</ul>

<hr>

<h3>Featured Song: </h3>


<% if Song.any? %>
  <h4><%= link_to @random_song.title, subgenre_song_path(@random_song.subgenre, @random_song) %> by <em><%= @random_song.artist %></em></h4>
<% end %>



<br><hr>

<h3>All songs available: (a-z)</h3>
  <% Song.all.order(title: :asc).each do |song| %>
    <li> <big><%= link_to song.title, subgenre_song_path(song.subgenre, song)  %></big>
       - by <em><%= song.artist %></em>
       - posted <%= time_ago_in_words(song.created_at)  %> ago </li>
  <% end %>
<br>

app/views/subgenres/new.html.erb
<h1>Add Subgenre</h1>


<%= render "form" %>

app/views/subgenres/show.html.erb
<div class="subgenres-header">
  <h1><%= @subgenres.name %></h1>  | <%= link_to "Edit Genre Name", edit_subgenre_path(@subgenres) %>  | <%= link_to "Delete Genre", subgenre_path(@subgenres),:data => {:confirm => "You sure?",:method => "delete"} %>
</div>

<br>
<div id="back-button">
  <%= link_to subgenres_path, class: "btn btn-xs btn-success" do %>
  <i class="glyphicon glyphicon-chevron-left"> Back</i>
  <% end %>
</div>

<hr><br>

<h3>Tha songz:</h3>

<br>

<ul>
  <% @subgenres.songs.order(created_at: :desc).each do |song| %>
    <li>
      <big><big><%= link_to song.title, subgenre_song_path(@subgenres, song) %></big></big>
      - <em><%= song.artist %></em>
      &nbsp;
      <big><%= link_to "▲",  subgenre_song_path(@subgenres, song, vote: "up"), :data => {:method => "patch"}  %><%= link_to "▼", subgenre_song_path(@subgenres, song, vote: "down"), :data => {:method => "patch"} %></big>
      <br>
       posted <%= time_ago_in_words(song.created_at)  %> ago
       - <%= link_to "Edit Song", edit_subgenre_song_path(@subgenres, song) %>
       | <%= link_to "Delete Song", subgenre_song_path(@subgenres, song),
          :data => {:confirm => "You Sure?",

            :method => "delete"}%>
      <%= link_to "Upvote",  upvote_subgenre_song_path(@subgenres,song), :data => {:method => "update"}  %>
      <%= link_to "Downvote", downvote_subgenre_song_path(@subgenres,song), :data => {:method => "update"} %>
      <%=song.upvote%>
      <%=song.downvote%>

  </li>
  <% end %>
</ul>

<br>
<p><%= link_to "Add a song to this genre", new_subgenre_song_path(@subgenres) %></p>
<br>